title: МУЗИЛКА(КУЗЯФОНК)
email: gd61@ro.ru
description: Официальный сайт МУЗИЛКА, также известный как КУЗЯФОНК. Тгк @kuzyafonk
baseurl: ""  # Если проект в подпапке
header_title: "Header Title"
url: "https://muzilka.github.io"
date_format: "%-d.%m.%Y"
baseurl: ""

# Навигация
navigation:
  - name: "Главная"
    link: "/"

# Соцсети
social:
  - name: "ВКонтакте"
    url: "https://vk.com/kuzina125"
  - name: "Telegram"
    url: "https://t.me/kuzyafonk"
