title: МУЗИЛКА(КУЗЯФОНК)
email: 
description: Официальный сайт МУЗИЛКА, также известный как КУЗЯФОНК. Тгк @kuzyafonk
baseurl: "/docs"  # Если проект в подпапке
url: ""      # Домен (можно оставить пустым для GitHub Pages)