title: МУЗИЛКА(КУЗЯФОНК)
email: 
description: Официальный сайт МУЗИЛКА, также известный как КУЗЯФОНК. Тгк @kuzyafonk
baseurl: ""  # Если проект в подпапке
header_title: "Header Title"
url: "https://muzilka.github.io"
date_format: "%-d.%m.%Y"
phone: "+7 (XXX) XXX-XX-XX"
baseurl: ""

# Навигация
navigation:
  - name: "Главная"
    link: "/"
  - name: "О нас"
    link: "/about"
  - name: "Услуги"
    link: "/services"
  - name: "Контакты"
    link: "/contacts"

# Соцсети
social:
  - name: "VK"
    url: "https://vk.com/ваша_страница"
  - name: "Telegram"
    url: "https://t.me/ваш_канал"