title: МУЗИЛКА(КУЗЯФОНК)
email: 
description: Официальный сайт МУЗИЛКА, также известный как КУЗЯФОНК. Тгк @kuzyafonk
baseurl: ""  # Если проект в подпапке
header_title: "Header Title"
url:         "https://muzilka.github.io"
date_format: "%-d.%m.%Y"